"""Auto-Reply Route Prompt Grading Engine & Prototyping Harness.

Evaluates and grades multi-turn prompt trajectories generated by the /q skill
against Operator DNA standards:
1. Domain Stratification (25 pts): Accurate intent mapping (Code vs. UX vs. Research)
2. Anti-Tower-of-Babel (20 pts): Pragmatic, least-complicated solutions over speculative bloat
3. Verification Rigor (20 pts): Concrete non-self-attesting verification (tests, exit code 0, screenshots)
4. Trajectory Momentum (20 pts): Coherent progression (Prototype -> Core -> Slop Audit -> Test -> Report)
5. Conciseness & Tone (15 pts): Terse, punchy phrasing (10-25 words), zero corporate throat-clearing
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
import json
import re
import sys
from typing import Any, Optional

from auto_reply_route.builder import generate_followup_queue
from auto_reply_route.queue_paster import parse_queue_command


@dataclass
class PillarScore:
    name: str
    score: float
    max_score: float
    feedback: str

    @property
    def percentage(self) -> float:
        return (self.score / self.max_score) * 100.0 if self.max_score > 0 else 0.0


@dataclass
class PromptGradeReport:
    raw_prompt: str
    parsed_prompt: str
    steps: int
    subagents: int
    domain: str
    subject: str
    pillars: dict[str, PillarScore]
    total_score: float
    letter_grade: str
    critiques: list[str]
    prompts: list[str]

    def to_dict(self) -> dict[str, Any]:
        return {
            "raw_prompt": self.raw_prompt,
            "parsed_prompt": self.parsed_prompt,
            "steps": self.steps,
            "subagents": self.subagents,
            "domain": self.domain,
            "subject": self.subject,
            "total_score": round(self.total_score, 1),
            "letter_grade": self.letter_grade,
            "pillars": {
                k: {
                    "score": round(v.score, 1),
                    "max": v.max_score,
                    "feedback": v.feedback,
                }
                for k, v in self.pillars.items()
            },
            "critiques": self.critiques,
            "prompts": self.prompts,
        }


_GRADE_THRESHOLDS = (
    (97.0, "A+"),
    (93.0, "A"),
    (90.0, "A-"),
    (87.0, "B+"),
    (83.0, "B"),
    (80.0, "B-"),
    (75.0, "C+"),
    (70.0, "C"),
    (60.0, "D"),
)


def _score_to_letter(score: float) -> str:
    for threshold, letter in _GRADE_THRESHOLDS:
        if score >= threshold:
            return letter
    return "F"


class PromptGrader:
    """Evaluates and grades multi-turn prompt sequences."""

    # Keywords signaling non-self-attesting verification
    VERIFICATION_SIGNALS = [
        r"\bexit code 0\b",
        r"\bpytest\b",
        r"\btests?\b",
        r"\bassertions?\b",
        r"\bscreenshot\b",
        r"\bverified functionality\b",
        r"\bwalkthrough report\b",
        r"\bproof\b",
    ]

    # Anti-patterns indicating speculative bloat or AI slop
    SLOP_PATTERNS = [
        r"\bgeneric plugin framework\b",
        r"\bextensible inheritance hierarchy\b",
        r"\babstract interface adapter factory\b",
        r"\bcomprehensive end-to-end architecture\b",
        r"\bplease note that\b",
        r"\bin order to\b",
    ]

    # Pragmatic engineering, UX craft, and venture research signals
    PRAGMATIC_SIGNALS = [
        r"\bleast complicated way\b",
        r"\bminimal\b",
        r"\bclean minimal code\b",
        r"\brefactor complex branches\b",
        r"\bslop\b",
        r"\bprototype\b",
        r"\bplain, welcoming everyday language\b",
        r"\b44px\b",
        r"\bconcentric radii\b",
        r"\bzero layout glitches\b",
        r"\brefute earlier claims\b",
        r"\bprobability of success\b",
        r"\bgo or no go\b",
    ]

    @classmethod
    def grade(
        cls,
        prompt: str,
        steps: Optional[int] = None,
        subagents: Optional[int] = None,
    ) -> PromptGradeReport:
        """Parses the prompt, generates the follow-up trajectory, and evaluates quality."""
        # 1. Parse command
        parsed_prompt, p_steps, p_subs = parse_queue_command(
            prompt,
            default_steps=steps if steps is not None else 5,
            default_subagents=subagents if subagents is not None else 0,
        )
        actual_steps = steps if steps is not None else p_steps
        actual_subs = subagents if subagents is not None else p_subs

        # 2. Generate trajectory
        manifest = generate_followup_queue(
            parsed_prompt, count=actual_steps, max_subagents=actual_subs
        )
        domain = manifest.metadata.get("domain", "code")
        subject = manifest.metadata.get("subject", parsed_prompt)
        prompts = [m.prompt for m in manifest.messages]

        critiques: list[str] = []

        # --- Pillar 1: Domain Stratification (25 pts) ---
        domain_score = 25.0
        domain_feedback = f"Accurately mapped to '{domain}' domain with clean context isolation."
        lower_prompt = parsed_prompt.lower()

        # Check for domain mismatches
        is_ux_intent = any(k in lower_prompt for k in ("tap", "ui", "css", "spacing", "modal", "radii", "drawer", "microcopy"))
        is_venture_intent = any(k in lower_prompt for k in ("cavitation", "device", "market", "venture", "business", "roi"))

        if is_ux_intent and domain != "ux":
            domain_score -= 15.0
            critiques.append("UI/UX intent misclassified as code/research.")
        elif is_venture_intent and domain != "research":
            domain_score -= 12.0
            critiques.append("Venture/science intent misclassified as code.")
        elif domain == "research" and not is_venture_intent and "research" not in lower_prompt:
            domain_score -= 10.0
            critiques.append("Coding task improperly assigned to research domain.")

        domain_score = max(0.0, domain_score)

        # --- Pillar 2: Anti-Tower-of-Babel & Simplicity (20 pts) ---
        babel_score = 20.0
        has_pragmatic = False
        for p in prompts:
            p_lower = p.lower()
            for pat in cls.SLOP_PATTERNS:
                if re.search(pat, p_lower):
                    babel_score -= 5.0
                    critiques.append(f"Prompt contains speculative/bloated language: {pat}")
            for pat in cls.PRAGMATIC_SIGNALS:
                if re.search(pat, p_lower):
                    has_pragmatic = True

        if not has_pragmatic:
            babel_score -= 4.0
            critiques.append("Trajectory lacks explicit 'least-complicated' / anti-slop mandate.")

        babel_score = max(0.0, min(20.0, babel_score))
        babel_feedback = "Strongly enforces minimal blast-radius and anti-slop constraints." if babel_score >= 18 else "Some risk of overengineering or missing pragmatic constraints."

        # --- Pillar 3: Verification Rigor (20 pts) ---
        verif_score = 0.0
        verified_steps = 0
        for p in prompts:
            p_lower = p.lower()
            if any(re.search(sig, p_lower) for sig in cls.VERIFICATION_SIGNALS):
                verified_steps += 1

        if verified_steps >= len(prompts) * 0.6:
            verif_score = 20.0
            verif_feedback = f"{verified_steps}/{len(prompts)} steps require concrete empirical verification."
        elif verified_steps > 0:
            verif_score = 14.0
            verif_feedback = f"Partial verification: {verified_steps}/{len(prompts)} steps anchored by tests/proof."
        else:
            verif_score = 5.0
            critiques.append("Trajectory lacks non-self-attesting empirical proof gates.")
            verif_feedback = "Weak verification: prompts rely on self-attestation."

        # --- Pillar 4: Trajectory Momentum (20 pts) ---
        traj_score = 20.0
        # Check that steps are distinct
        unique_prompts = set(prompts)
        if len(unique_prompts) < len(prompts):
            traj_score -= 8.0
            critiques.append("Duplicate or repetitive steps detected in trajectory.")

        # Check for natural progression
        if len(prompts) >= 3:
            first_p = prompts[0].lower()
            last_p = prompts[-1].lower()
            if "report" in first_p or "sign-off" in first_p:
                traj_score -= 6.0
                critiques.append("Premature closure: Step 1 asks for final report.")
            if "report" not in last_p and "walkthrough" not in last_p and "sign-off" not in last_p:
                traj_score -= 2.0
                critiques.append("Missing explicit delivery/report phase in final step.")

        traj_score = max(0.0, min(20.0, traj_score))
        traj_feedback = "Coherent multi-step arc from inception to verification and final delivery."

        # --- Pillar 5: Conciseness & Tone (15 pts) ---
        tone_score = 15.0
        word_counts = [len(p.split()) for p in prompts]
        avg_words = sum(word_counts) / len(word_counts) if word_counts else 0

        for wc in word_counts:
            if wc > 45:
                tone_score -= 1.5
            elif wc < 6:
                tone_score -= 1.0

        for p in prompts:
            if re.search(r"\b(please note|in order to|you should now)\b", p.lower()):
                tone_score -= 2.0
                critiques.append("Corporate throat-clearing fluff detected.")

        tone_score = max(0.0, min(15.0, tone_score))
        tone_feedback = f"Terse and actionable (avg {avg_words:.0f} words/step), zero fluff."

        # Compute totals
        pillars = {
            "domain_fit": PillarScore("Domain Stratification", domain_score, 25.0, domain_feedback),
            "anti_babel": PillarScore("Anti-Tower-of-Babel", babel_score, 20.0, babel_feedback),
            "verification": PillarScore("Verification Rigor", verif_score, 20.0, verif_feedback),
            "trajectory": PillarScore("Trajectory Momentum", traj_score, 20.0, traj_feedback),
            "tone": PillarScore("Conciseness & Tone", tone_score, 15.0, tone_feedback),
        }
        total_score = sum(p.score for p in pillars.values())
        letter = _score_to_letter(total_score)

        return PromptGradeReport(
            raw_prompt=prompt,
            parsed_prompt=parsed_prompt,
            steps=actual_steps,
            subagents=actual_subs,
            domain=domain,
            subject=subject,
            pillars=pillars,
            total_score=total_score,
            letter_grade=letter,
            critiques=critiques,
            prompts=prompts,
        )


def format_grade_card(report: PromptGradeReport) -> str:
    """Renders a beautiful, high-contrast terminal grade report card."""
    lines: list[str] = []
    lines.append("=" * 72)
    lines.append(f" 📊 PROMPT TRAJECTORY GRADE CARD: [{report.letter_grade}] ({report.total_score:.1f}/100)")
    lines.append("=" * 72)
    lines.append(f"  Seed Input:    {report.raw_prompt}")
    lines.append(f"  Parsed Scope:  {report.parsed_prompt}")
    lines.append(f"  Domain:        {report.domain.upper()} | Steps: {report.steps} | Subagents: {report.subagents}")
    lines.append(f"  Subject:       {report.subject}")
    lines.append("-" * 72)
    lines.append("  Pillar Breakdown:")
    for key, p in report.pillars.items():
        bar_filled = int(p.percentage / 10)
        bar = "█" * bar_filled + "░" * (10 - bar_filled)
        lines.append(f"    [{bar}] {p.score:4.1f}/{p.max_score:<4.1f} ({p.percentage:5.1f}%) {p.name}")
        lines.append(f"           ↳ {p.feedback}")

    if report.critiques:
        lines.append("-" * 72)
        lines.append("  🔍 Targeted Critique & Polish Notes:")
        for c in report.critiques:
            lines.append(f"    • {c}")

    lines.append("-" * 72)
    lines.append(f"  Generated Trajectory ({len(report.prompts)} Steps):")
    for idx, p in enumerate(report.prompts, 1):
        lines.append(f"    {idx}. {p}")
    lines.append("=" * 72)
    return "\n".join(lines)


STANDARD_BENCHMARKS = [
    "/q dental cavitation plaque removal device 5 steps",
    "/q audit mobile checkout drawer for 44px tap targets and microcopy",
    "/q build Stripe billing checkout webhook router with 3 subagents and 5 turns",
    "fix race condition in websocket connection manager with 3 turns",
    "/q 404 error page responsive redesign with 4 turns",
    "/q 5 (3 subagents) refactor auth token rotation",
    "/q cache",
    "/q stop using redux and migrate to zustand with 4 steps",
]


def run_benchmark_suite() -> list[PromptGradeReport]:
    """Runs grading across the full suite of standard prompt archetypes."""
    reports = [PromptGrader.grade(p) for p in STANDARD_BENCHMARKS]
    return reports


def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate and grade /q prompt trajectories.")
    parser.add_argument("prompt", nargs="?", default=None, help="Prompt to evaluate")
    parser.add_argument("--steps", "-n", type=int, default=None, help="Step count override")
    parser.add_argument("--subagents", "-s", type=int, default=None, help="Subagents count override")
    parser.add_argument("--all", action="store_true", help="Run full benchmark archetype suite")
    parser.add_argument("--json", action="store_true", help="Output machine-readable JSON")

    args = parser.parse_args()

    if args.all:
        reports = run_benchmark_suite()
        if args.json:
            print(json.dumps([r.to_dict() for r in reports], indent=2))
        else:
            print(f"\n📋 Evaluating {len(reports)} Standard Prompt Archetypes...\n")
            for r in reports:
                print(format_grade_card(r))
                print()
            avg_score = sum(r.total_score for r in reports) / len(reports)
            avg_letter = _score_to_letter(avg_score)
            print("=" * 72)
            print(f" 🏆 BENCHMARK SUITE AVERAGE: [{avg_letter}] {avg_score:.1f}/100 across {len(reports)} tests")
            print("=" * 72)
        return 0

    target_prompt = args.prompt or "Build Stripe billing webhook router with 3 turns"
    report = PromptGrader.grade(target_prompt, steps=args.steps, subagents=args.subagents)

    if args.json:
        print(json.dumps(report.to_dict(), indent=2))
    else:
        print(format_grade_card(report))

    return 0


if __name__ == "__main__":
    sys.exit(main())
