"""Subagent Team Orchestrator and Review Synthesis Engine.

Implements multi-persona subagent teams, deterministic review synthesis,
living-room verdict generation, and Stratum 3 screenshot evidence manifests.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
import re
from typing import Any, Optional


@dataclass
class AgentPersona:
    """Specialized subagent persona with bounded evaluation mandate."""

    name: str
    role: str
    focus_areas: list[str]
    system_prompt: str
    evaluation_heuristics: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "role": self.role,
            "focus_areas": list(self.focus_areas),
            "system_prompt": self.system_prompt,
            "evaluation_heuristics": list(self.evaluation_heuristics),
        }


@dataclass
class SubagentTeam:
    """Multi-persona review team deployed for a discrete verification turn."""

    team_id: str
    name: str
    personas: list[AgentPersona]
    mandate: str
    verdict_criteria: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "team_id": self.team_id,
            "name": self.name,
            "personas": [p.to_dict() for p in self.personas],
            "mandate": self.mandate,
            "verdict_criteria": list(self.verdict_criteria),
        }


@dataclass
class PersonaCritique:
    """Individual critique generated by a subagent persona."""

    persona_name: str
    role: str
    passed: bool
    critique: str
    issues: list[str] = field(default_factory=list)
    recommendations: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "persona_name": self.persona_name,
            "role": self.role,
            "passed": self.passed,
            "critique": self.critique,
            "issues": list(self.issues),
            "recommendations": list(self.recommendations),
        }


@dataclass
class TeamReviewVerdict:
    """Aggregated outcome of a multi-persona team review."""

    team_type: str
    team_name: str
    passed: bool
    living_room_verdict: str
    critiques: list[PersonaCritique] = field(default_factory=list)
    defects: list[str] = field(default_factory=list)
    compromises: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def __bool__(self) -> bool:
        return self.passed

    def to_dict(self) -> dict[str, Any]:
        return {
            "team_type": self.team_type,
            "team_name": self.team_name,
            "passed": self.passed,
            "living_room_verdict": self.living_room_verdict,
            "critiques": [c.to_dict() for c in self.critiques],
            "defects": list(self.defects),
            "compromises": list(self.compromises),
            "metadata": dict(self.metadata),
        }

    def to_markdown(self) -> str:
        """Format verdict into clean, customer-facing Markdown."""
        status_badge = "✅ **VERDICT: APPROVED**" if self.passed else "❌ **VERDICT: REJECTED**"
        lines = [
            f"## {self.team_name} — Review Verdict",
            "",
            status_badge,
            "",
            f"**Summary:** {self.living_room_verdict}",
            "",
        ]

        if self.defects:
            lines.append("### 🐛 Identified Defects")
            for d in self.defects:
                lines.append(f"- {d}")
            lines.append("")

        if self.compromises:
            lines.append("### ⚠️ Architectural Compromises & Debt")
            for c in self.compromises:
                lines.append(f"- {c}")
            lines.append("")

        if self.critiques:
            lines.append("### 👥 Subagent Persona Reports")
            for c in self.critiques:
                badge = "PASS" if c.passed else "FAIL"
                lines.append(f"#### [{badge}] {c.persona_name} ({c.role})")
                lines.append(f"{c.critique}")
                if c.issues:
                    lines.append("Issues noted:")
                    for issue in c.issues:
                        lines.append(f"  - {issue}")
                if c.recommendations:
                    lines.append("Recommendations:")
                    for rec in c.recommendations:
                        lines.append(f"  - {rec}")
                lines.append("")

        return "\n".join(lines).strip()


# Precompiled regex patterns for adversarial audit synthesis
_QA_EDGE_RE = re.compile(
    r"\b(?:unhandled\s+(?:null|none)|off-by-one|infinite\s+loop|deadlock|race\s+condition)\b[^.\n]*",
    re.IGNORECASE,
)
_QA_SHELL_TRUE_RE = re.compile(r"shell\s*=\s*True")
_QA_DYNAMIC_EXEC_RE = re.compile(r"\b(?:eval|exec)\s*\(")
_QA_CREDENTIALS_RE = re.compile(r"\b(?:sk-[a-zA-Z0-9]{15,}|AIza[0-9A-Za-z-_]{30,}|AKIA[0-9A-Z]{16})\b")
_QA_SEC_VULN_RE = re.compile(r"\b(?:security\s+vulnerability|injection\s+risk|auth\s+bypass)[^.\n]*", re.IGNORECASE)
_QA_TAUTOLOGICAL_RE = re.compile(r"assert\s+(?:True|1\s*==\s*1|not\s+False)\b")
_QA_SKIPPED_RE = re.compile(r"@pytest\.mark\.skip|@unittest\.skip|\.skipTest\(")
_QA_EMPTY_STUB_RE = re.compile(r"def\s+test_[a-zA-Z0-9_]+\s*\([^)]*\)\s*:\s*(?:pass|\.\.\.)\s*$", re.MULTILINE)
_QA_FAILURES_RE = re.compile(r"\b(?:=== FAILURES ===|FAILED \(failures=|\bAssertionError\b)")

_EXEC_PLUMBING_RE = re.compile(
    r"\b(?:internal\s+server\s+error|database\s+connection\s+failed|sql\s+syntax\s+error|fetch\s+records\s+from\s+backend)\b",
    re.IGNORECASE,
)
_EXEC_COMPLEXITY_RE = re.compile(
    r"\b(?:overengineered|accidental\s+complexity|unnecessary\s+abstraction\s+layer)\b",
    re.IGNORECASE,
)
_EXEC_HACK_PATTERNS = [
    (re.compile(r"\b(?:TODO:?\s*hack|FIXME|HACK:?\s*temporary|workaround\s+for\s+now)\b", re.IGNORECASE), "Temporary hack or workaround marker"),
    (re.compile(r"\b(?:monkey\s*patch|monkeypatching)\b", re.IGNORECASE), "Monkey patching detected in implementation"),
    (re.compile(r"\b(?:revisit\s+later|quick\s+fix\s+for\s+now|ugly\s+hack)\b", re.IGNORECASE), "Acknowledged technical debt or quick-fix shortcut"),
    (re.compile(r"\b(?:compromise\s+taken|rabbit\s+hole\s+gone\s+down)\b", re.IGNORECASE), "Unacceptable architectural compromise or rabbit hole"),
]
_EXEC_PRODUCT_RE = re.compile(
    r"\b(?:feature\s+incomplete|broken\s+user\s+flow|confusing\s+ux|missing\s+core\s+requirement)\b",
    re.IGNORECASE,
)

_INTEG_WIRING_PATTERNS = [
    (re.compile(r"\b(?:ImportError|ModuleNotFoundError)\b"), "Broken module import encountered"),
    (re.compile(r"\bAttributeError:\s*module\s+.*has\s+no\s+attribute\b"), "Missing attribute or function in module wiring"),
    (re.compile(r"\bTypeError:\s*.*missing\s+\d+\s+required\s+positional\s+argument\b"), "Mismatched function call signature"),
    (re.compile(r"\b(?:wiring\s+defect|wiring\s+error|unwired\s+component)\b", re.IGNORECASE), "Wiring defect identified between components"),
    (re.compile(r"\bNotImplementedError\b"), "Unwired stub (NotImplementedError) remaining in pipeline"),
]
_INTEG_REGRESSION_RE = re.compile(
    r"\b(?:regression\s+detected|breaking\s+change\s+to\s+public\s+api|broke\s+existing\s+tests?)\b",
    re.IGNORECASE,
)
_INTEG_STATE_RE = re.compile(
    r"\b(?:state\s+desync|data\s+loss|unsynced\s+cache|dirty\s+write|concurrency\s+race\s+on\s+state)\b",
    re.IGNORECASE,
)

_VISUAL_CRAFT_PATTERNS = [
    (re.compile(r"\b(?:sub-44px|tap\s+target\s+too\s+small|hitbox\s*<\s*44)\b", re.IGNORECASE), "Sub-44px tap hitbox violates touch ergonomics"),
    (re.compile(r"\b(?:off-grid\s+pixel|arbitrary\s+margin|5px|7px|13px)\b", re.IGNORECASE), "Off-grid spacing violates 4/8pt rhythm"),
    (re.compile(r"\b(?:pinched\s+corner|nested\s+radius\s+distortion)\b", re.IGNORECASE), "Pinched nested corner radius violates concentricity"),
    (re.compile(r"\b(?:contrast\s+too\s+low|unreadable\s+text|layout\s+shift)\b", re.IGNORECASE), "Visual contrast or layout shift defect"),
    (re.compile(r"\b(?:screenshot\s+missing|image\s+not\s+found|failed\s+to\s+capture)\b", re.IGNORECASE), "Missing or corrupt screenshot evidence"),
]

_GENERIC_FAILURE_RE = re.compile(r"\b(?:FAILED|ERROR|EXCEPTION|REJECTED)\b", re.IGNORECASE)


class SubagentTeamOrchestrator:
    """Orchestrates multi-persona teams for discrete verification turns."""

    # 1. QA Team Personas (First Pass)
    EDGE_CASE_AUDITOR = AgentPersona(
        name="Edge Case Auditor",
        role="edge_case_auditor",
        focus_areas=[
            "boundary values",
            "null / empty handling",
            "concurrency & race conditions",
            "timeouts & resource leaks",
            "unhandled exceptions",
        ],
        system_prompt=(
            "You are an adversarial Edge Case Auditor. Scrutinize code for off-by-one errors, "
            "missing bounds checking, unhandled None/null values, timeout enforcement, "
            "and race conditions under high concurrency."
        ),
        evaluation_heuristics=[
            "Check for unbounded collections or missing size limits",
            "Verify timeouts on external commands, network requests, and locks",
            "Ensure None-checks exist before attribute lookups or slicing",
        ],
    )

    SECURITY_AUDITOR = AgentPersona(
        name="Security Auditor",
        role="security_auditor",
        focus_areas=[
            "injection vulnerabilities",
            "credential / secret exposure",
            "path traversal",
            "unsafe execution (eval/exec/shell=True)",
            "test skip bypasses",
        ],
        system_prompt=(
            "You are a rigorous Security Auditor. Audit code for shell injection, command concatenation, "
            "path traversal, unescaped queries, credential leaks, and fraudulent test skip annotations."
        ),
        evaluation_heuristics=[
            "Reject eval, exec, and unescaped shell=True invocations",
            "Reject hardcoded tokens, API keys, or private credentials",
            "Flag path traversal vectors (e.g. '../' without canonicalization)",
        ],
    )

    TEST_COVERAGE_SPECIALIST = AgentPersona(
        name="Test Coverage Specialist",
        role="test_coverage_specialist",
        focus_areas=[
            "assertion rigor",
            "anti-cheat detection (assert True, empty test stubs)",
            "mutation resilience",
            "mock realism",
            "deterministic repeatability",
        ],
        system_prompt=(
            "You are a Test Coverage Specialist. Detect and strike down tautological assertions "
            "(assert True, assert 1 == 1), empty test bodies, skipped tests under pressure, "
            "and brittle mocking shortcuts."
        ),
        evaluation_heuristics=[
            "Strike down tests with zero assertions or tautological asserts",
            "Flag @pytest.mark.skip and @unittest.skip bypasses",
            "Verify all negative failure branches and exception paths are tested",
        ],
    )

    # 2. Executive Review Team Personas
    SIMPLICITY_AUDITOR = AgentPersona(
        name="Simplicity Auditor",
        role="simplicity_auditor",
        focus_areas=[
            "tower of babel prevention",
            "accidental complexity",
            "living-room test compliance",
            "zero plumbing exposure",
            "excessive abstractions",
            "cognitive friction",
        ],
        system_prompt=(
            "You are a Simplicity Auditor. Make sure we have not built a tower of babel here and "
            "be completely honest about where things are at. Eliminate overengineering, delete unnecessary "
            "wrapper classes, flatten deep indentation, and enforce the Living-Room Test: if user copy "
            "describes internal mechanics or server plumbing, reject it immediately."
        ),
        evaluation_heuristics=[
            "Make sure we have not built a tower of babel: reject overengineered abstractions and ungrounded complexity",
            "Enforce honest reality reporting: reject false claims of production readiness where fragile heuristics exist",
            "Reject user-facing strings that expose database or server plumbing",
            "Flag functions exceeding 80 lines without clear linear progression",
            "Eliminate premature abstractions that solve hypothetical future problems",
        ],
    )

    TECHNICAL_DEBT_OFFICER = AgentPersona(
        name="Technical Debt Officer",
        role="technical_debt_officer",
        focus_areas=[
            "temporary hacks & workarounds",
            "unhandled TODOs and FIXMEs",
            "monkey patching",
            "architectural compromises",
            "long-term maintainability",
        ],
        system_prompt=(
            "You are an uncompromising Technical Debt Officer. Reject code containing temporary hacks, "
            "unresolved TODOs, monkey patches, or architectural compromises that an executive would veto."
        ),
        evaluation_heuristics=[
            "Flag TODO: hack, FIXME, monkey patch, and temporary workaround markers",
            "Ensure resource allocation uses proper context managers and finalizers",
            "Reject brittle assumptions that break under architectural shifts",
        ],
    )

    PRODUCT_DIRECTOR = AgentPersona(
        name="Product Director",
        role="product_director",
        focus_areas=[
            "user value delivery",
            "stress-free UX",
            "intuitive workflows",
            "delight and micro-polish",
            "feature completeness",
        ],
        system_prompt=(
            "You are a customer-focused Product Director. Ensure the feature directly and delightfully "
            "solves the user's intent without confusion, extra steps, or technical intimidation."
        ),
        evaluation_heuristics=[
            "Verify customer experience is friction-free and obvious from the first second",
            "Ensure error recovery provides friendly, helpful next steps",
            "Confirm all acceptance criteria from the original user request are fulfilled",
        ],
    )

    # 3. System Integration Team Personas
    WIRING_LOGIC_AUDITOR = AgentPersona(
        name="Wiring Logic Auditor",
        role="wiring_logic_auditor",
        focus_areas=[
            "caller / callee signatures",
            "parameter forwarding",
            "export manifests (__all__)",
            "import graph integrity",
            "dependency injection",
        ],
        system_prompt=(
            "You are a Wiring Logic Auditor. Trace function signatures, verify argument passing, "
            "validate __all__ package exports, and eliminate broken imports or dangling stubs."
        ),
        evaluation_heuristics=[
            "Verify all exported symbols in __all__ exist and are importable",
            "Check that callers provide all required positional arguments",
            "Reject stubbed implementations (NotImplementedError, pass # stub)",
        ],
    )

    REGRESSIONS_CHECKER = AgentPersona(
        name="Regressions Checker",
        role="regressions_checker",
        focus_areas=[
            "backward compatibility",
            "legacy test suite health",
            "public API stability",
            "breaking schema changes",
        ],
        system_prompt=(
            "You are a Regressions Checker. Ensure no existing public APIs, CLI commands, "
            "or test suites are broken by new additions."
        ),
        evaluation_heuristics=[
            "Verify existing public class and method signatures remain backward-compatible",
            "Ensure serialization schemas support legacy data formats",
            "Confirm legacy test files pass without modifications",
        ],
    )

    STATE_SYNC_SPECIALIST = AgentPersona(
        name="State Sync Specialist",
        role="state_sync_specialist",
        focus_areas=[
            "thread-safe mutation",
            "atomic disk persistence",
            "cache coherence",
            "idempotent state transitions",
        ],
        system_prompt=(
            "You are a State Sync Specialist. Audit state transitions, verify atomic file replacement "
            "and POSIX directory sync, and eliminate race conditions across concurrent processes."
        ),
        evaluation_heuristics=[
            "Ensure disk writes use atomic tempfiles and fsync",
            "Verify state machine transitions are idempotent and guarded by locks",
            "Prevent stale in-memory state after file modifications",
        ],
    )

    # 4. Visual Proof Team Personas
    SCREENSHOT_VERIFIER = AgentPersona(
        name="Screenshot / Simulator Verifier",
        role="screenshot_verifier",
        focus_areas=[
            "visual proof fidelity",
            "6-lens UI/UX craft standard",
            "concentric radii (R_inner = max(0, R_outer - P))",
            "strict 4/8pt spatial rhythm",
            "touch ergonomics (>= 44x44px)",
            "contrast and zero layout shift",
        ],
        system_prompt=(
            "You are a Visual Proof and Craft Verifier. Audit captured screenshots and simulator logs "
            "against the 6-Lens Micro-Craft Standard: 4/8pt rhythm, concentric radii, 44x44px minimum hitboxes, "
            "contrast ratios, and zero layout shift."
        ),
        evaluation_heuristics=[
            "Verify screenshot files exist on disk with valid dimensions",
            "Check touch targets meet Apple HIG minimum (44x44px)",
            "Enforce concentric corner radii and strict 4/8pt spatial grid",
        ],
    )

    WALKTHROUGH_AUDITOR = AgentPersona(
        name="Walkthrough Auditor",
        role="walkthrough_auditor",
        focus_areas=[
            "end-to-end user journey",
            "documentation completeness",
            "before / after evidence",
            "living-room friendliness",
        ],
        system_prompt=(
            "You are a Walkthrough Auditor. Ensure documentation and walkthrough cards present "
            "a complete, clear, and reassuring visual narrative of verified functionality."
        ),
        evaluation_heuristics=[
            "Verify all user story steps are visually demonstrated",
            "Ensure copy adheres to the Zero Plumbing Law and passes the Living-Room Test",
            "Confirm before and after states are clearly documented",
        ],
    )

    def __init__(self) -> None:
        """Initialize orchestrator with standard multi-persona teams."""
        self._teams: dict[str, SubagentTeam] = {
            "qa_team": SubagentTeam(
                team_id="qa_team",
                name="3-Person QA Team (First Pass)",
                personas=[
                    self.EDGE_CASE_AUDITOR,
                    self.SECURITY_AUDITOR,
                    self.TEST_COVERAGE_SPECIALIST,
                ],
                mandate="Audit boundary values, security vulnerabilities, and test assertion rigor.",
                verdict_criteria=[
                    "Zero unhandled edge cases or missing boundary checks",
                    "Zero security vulnerabilities or skipped tests",
                    "Zero tautological assertions (assert True)",
                ],
            ),
            "qa_team_2": SubagentTeam(
                team_id="qa_team_2",
                name="3-Person QA Team (Second Independent Pass)",
                personas=[
                    AgentPersona(
                        name="Chaos & Resiliency Auditor",
                        role="chaos_auditor",
                        focus_areas=[
                            "unexpected error states",
                            "process crash resilience",
                            "poison pill payloads",
                            "high-frequency calls",
                        ],
                        system_prompt=(
                            "You are a fresh Chaos & Resiliency Auditor with zero cognitive bias. "
                            "Adversarially probe error recovery paths, malformed payloads, and process survival."
                        ),
                    ),
                    AgentPersona(
                        name="Threat Model Specialist",
                        role="threat_model_specialist",
                        focus_areas=[
                            "escalation paths",
                            "data boundary leakage",
                            "sanitization bypasses",
                            "subagent communication safety",
                        ],
                        system_prompt=(
                            "You are a Threat Model Specialist. Audit inter-agent messaging, "
                            "data exposure, and secret hygiene across all execution boundaries."
                        ),
                    ),
                    AgentPersona(
                        name="Invariant & Contract Specialist",
                        role="contract_specialist",
                        focus_areas=[
                            "strict schema conformance",
                            "serialization roundtrips",
                            "state machine invariants",
                        ],
                        system_prompt=(
                            "You are an Invariant & Contract Specialist. Verify dataclass schemas, "
                            "serialization round-trips, and state transition invariants."
                        ),
                    ),
                ],
                mandate="Conduct an independent second-pass verification with zero cognitive bias.",
                verdict_criteria=[
                    "Zero unhandled recovery paths",
                    "Zero data boundary leakage",
                    "100% invariant preservation",
                ],
            ),
            "executive_team": SubagentTeam(
                team_id="executive_team",
                name="Executive Review Team",
                personas=[
                    self.SIMPLICITY_AUDITOR,
                    self.TECHNICAL_DEBT_OFFICER,
                    self.PRODUCT_DIRECTOR,
                ],
                mandate="Scrutinize architecture for compromises, technical debt, and zero-plumbing simplicity.",
                verdict_criteria=[
                    "Zero technical debt, unhandled TODOs, or monkey patches",
                    "Living-Room Test compliance (zero exposed server plumbing)",
                    "Clean, linear, and stress-free user experience",
                ],
            ),
            "system_integration_team": SubagentTeam(
                team_id="system_integration_team",
                name="System Integration Team",
                personas=[
                    self.WIRING_LOGIC_AUDITOR,
                    self.REGRESSIONS_CHECKER,
                    self.STATE_SYNC_SPECIALIST,
                ],
                mandate="Verify caller/callee wiring, regression safety, and state synchronization.",
                verdict_criteria=[
                    "All public exports and callers cleanly wired",
                    "Zero regressions in existing test suite or models",
                    "Atomic, thread-safe state persistence",
                ],
            ),
            "visual_proof_team": SubagentTeam(
                team_id="visual_proof_team",
                name="Visual Proof Team",
                personas=[
                    self.SCREENSHOT_VERIFIER,
                    self.WALKTHROUGH_AUDITOR,
                ],
                mandate="Verify visual screenshot proof, 6-lens craft standards, and walkthrough completeness.",
                verdict_criteria=[
                    "Screenshot evidence verified and attached",
                    "6-Lens Micro-Craft standard compliance (radii, rhythm, touch hitboxes >= 44px)",
                    "Complete, living-room friendly user walkthrough",
                ],
            ),
        }

        # Normalize alias mapping
        self._aliases: dict[str, str] = {
            "qa": "qa_team",
            "qa1": "qa_team",
            "qa_team_1": "qa_team",
            "3_person_qa": "qa_team",
            "3_person_qa_team": "qa_team",
            "qa_team_2": "qa_team_2",
            "qa2": "qa_team_2",
            "second_qa": "qa_team_2",
            "second_qa_team": "qa_team_2",
            "another_qa": "qa_team_2",
            "another_3_person_qa": "qa_team_2",
            "executive": "executive_team",
            "exec": "executive_team",
            "executive_review": "executive_team",
            "executive_review_team": "executive_team",
            "integration": "system_integration_team",
            "wiring": "system_integration_team",
            "system_integration": "system_integration_team",
            "wiring_logic": "system_integration_team",
            "visual": "visual_proof_team",
            "visual_proof": "visual_proof_team",
            "screenshot": "visual_proof_team",
            "screenshots": "visual_proof_team",
            "walkthrough": "visual_proof_team",
        }

    def list_teams(self) -> list[str]:
        """Return list of canonical team IDs."""
        return list(self._teams.keys())

    def get_team(self, team_type: str) -> SubagentTeam:
        """Resolve team instance by canonical ID or alias."""
        clean = re.sub(r"[^a-zA-Z0-9_]+", "_", team_type.strip().lower()).strip("_")
        canonical_id = self._aliases.get(clean, clean)
        if canonical_id not in self._teams:
            available = ", ".join(self._teams.keys())
            raise KeyError(f"Unknown team type '{team_type}'. Available teams: {available}")
        return self._teams[canonical_id]

    def build_team_prompt(self, team_type: str, context: str) -> str:
        """Generate structured multi-persona dispatch prompt."""
        team = self.get_team(team_type)
        lines = [
            f"# Multi-Persona Subagent Dispatch: {team.name}",
            "",
            f"**Mandate:** {team.mandate}",
            "",
            "## Personas & Verification Directives",
        ]
        for p in team.personas:
            lines.append(f"### Persona: {p.name} ({p.role})")
            lines.append(f"- **Focus Areas:** {', '.join(p.focus_areas)}")
            lines.append(f"- **System Directive:** {p.system_prompt}")
            lines.append("")

        lines.extend([
            "## Target Context / Implementation Under Review",
            "```",
            context.strip(),
            "```",
            "",
            "Conduct your adversarial audit. For each persona, report:",
            "- Status: PASS | FAIL",
            "- Specific issues or compromises identified",
            "- Concrete recommendations or required fixes",
        ])
        return "\n".join(lines)

    # ----------------------------------------------------------------------
    # Synthesis Engine: synthesize_team_review
    # ----------------------------------------------------------------------

    def synthesize_team_review(self, team_type: str, step_output: str) -> TeamReviewVerdict:
        """Aggregates subagent critiques into a structured living-room verdict.

        Identifies code defects, wiring logic flaws, or executive-level compromises.
        """
        team = self.get_team(team_type)
        raw_text = step_output.strip()

        # Check for empty output
        if not raw_text:
            critique = PersonaCritique(
                persona_name="Team Reviewer",
                role="auditor",
                passed=False,
                critique="No implementation output or review artifacts were provided for evaluation.",
                issues=["Empty step output received"],
                recommendations=["Provide the code, test execution logs, or visual evidence to review."],
            )
            return TeamReviewVerdict(
                team_type=team.team_id,
                team_name=team.name,
                passed=False,
                living_room_verdict=(
                    "Nothing was submitted for review yet. The team needs to see the code or "
                    "test results before checking it."
                ),
                critiques=[critique],
                defects=["Missing step output"],
                compromises=[],
            )

        # Run persona-specific audits based on team mandate
        canonical = team.team_id
        if canonical in ("qa_team", "qa_team_2"):
            return self._synthesize_qa_review(team, raw_text)
        elif canonical == "executive_team":
            return self._synthesize_executive_review(team, raw_text)
        elif canonical == "system_integration_team":
            return self._synthesize_integration_review(team, raw_text)
        elif canonical == "visual_proof_team":
            return self._synthesize_visual_review(team, raw_text)
        else:
            return self._synthesize_generic_review(team, raw_text)

    # ----------------------------------------------------------------------
    # Persona Audit Evaluators
    # ----------------------------------------------------------------------

    def _synthesize_qa_review(self, team: SubagentTeam, text: str) -> TeamReviewVerdict:
        """Synthesizes review for 3-Person QA teams."""
        defects: list[str] = []
        critiques: list[PersonaCritique] = []

        # 1. Edge Case Auditor
        edge_issues: list[str] = []
        match = _QA_EDGE_RE.search(text)
        if match:
            snippet = match.group(0).strip()
            edge_issues.append(f"Edge case flaw: {snippet}")

        if "zero_division" in text.lower() or "division by zero" in text.lower():
            edge_issues.append("Unhandled division by zero hazard")

        passed_edge = len(edge_issues) == 0
        defects.extend(edge_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[0].name,
                role=team.personas[0].role,
                passed=passed_edge,
                critique=(
                    "Boundary conditions and concurrency constraints passed without defects."
                    if passed_edge
                    else f"Flagged {len(edge_issues)} edge case hazard(s) requiring defensive guards."
                ),
                issues=edge_issues,
                recommendations=["Add explicit boundary guards and timeout controls."] if edge_issues else [],
            )
        )

        # 2. Security Auditor
        sec_issues: list[str] = []
        if _QA_SHELL_TRUE_RE.search(text) and ("shlex" not in text and "safe" not in text.lower()):
            sec_issues.append("Unsanitized shell=True invocation detected")

        if _QA_DYNAMIC_EXEC_RE.search(text):
            sec_issues.append("Unsafe dynamic code execution (eval/exec)")

        if _QA_CREDENTIALS_RE.search(text):
            sec_issues.append("Hardcoded API token or credential pattern discovered")

        sec_match = _QA_SEC_VULN_RE.search(text)
        if sec_match:
            snippet = sec_match.group(0).strip()
            sec_issues.append(f"Security vulnerability: {snippet}")

        passed_sec = len(sec_issues) == 0
        defects.extend(sec_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[1].name,
                role=team.personas[1].role,
                passed=passed_sec,
                critique=(
                    "Zero security vulnerabilities or secret leaks discovered."
                    if passed_sec
                    else f"Discovered {len(sec_issues)} security hazard(s)."
                ),
                issues=sec_issues,
                recommendations=["Use parameter tokenization and remove hardcoded tokens."] if sec_issues else [],
            )
        )

        # 3. Test Coverage Specialist
        test_issues: list[str] = []
        if _QA_TAUTOLOGICAL_RE.search(text):
            test_issues.append("Tautological assertion (assert True) detected in test suite")

        if _QA_SKIPPED_RE.search(text):
            test_issues.append("Skipped test annotation detected — tests must run green without skipping")

        if _QA_EMPTY_STUB_RE.search(text):
            test_issues.append("Empty test stub (pass/...) detected")

        if _QA_FAILURES_RE.search(text):
            test_issues.append("Test assertion failure recorded in test run")

        passed_test = len(test_issues) == 0
        defects.extend(test_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[2].name,
                role=team.personas[2].role,
                passed=passed_test,
                critique=(
                    "Test coverage is rigorous with authentic assertions and zero skips."
                    if passed_test
                    else f"Identified {len(test_issues)} test rigor defect(s)."
                ),
                issues=test_issues,
                recommendations=["Replace tautological or skipped assertions with concrete validations."] if test_issues else [],
            )
        )

        overall_passed = len(defects) == 0
        living_room = self._format_living_room_verdict(
            team=team,
            passed=overall_passed,
            defects=defects,
            compromises=[],
            critiques=critiques,
        )

        return TeamReviewVerdict(
            team_type=team.team_id,
            team_name=team.name,
            passed=overall_passed,
            living_room_verdict=living_room,
            critiques=critiques,
            defects=defects,
            compromises=[],
            metadata={"total_defects": len(defects)},
        )

    def _synthesize_executive_review(self, team: SubagentTeam, text: str) -> TeamReviewVerdict:
        """Synthesizes review for the Executive Review Team (simplicity, debt, product)."""
        defects: list[str] = []
        compromises: list[str] = []
        critiques: list[PersonaCritique] = []

        # 1. Simplicity Auditor
        simplicity_issues: list[str] = []
        if _EXEC_PLUMBING_RE.search(text):
            simplicity_issues.append("Internal server or database plumbing exposed to user-facing copy")

        if _EXEC_COMPLEXITY_RE.search(text):
            simplicity_issues.append("Unnecessary architectural complexity or abstraction bloat")

        passed_simplicity = len(simplicity_issues) == 0
        compromises.extend(simplicity_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[0].name,
                role=team.personas[0].role,
                passed=passed_simplicity,
                critique=(
                    "Clean linear implementation passing the Living-Room Test."
                    if passed_simplicity
                    else f"Flagged {len(simplicity_issues)} complexity or plumbing leak(s)."
                ),
                issues=simplicity_issues,
                recommendations=["Simplify abstractions and remove plumbing jargon."] if simplicity_issues else [],
            )
        )

        # 2. Technical Debt Officer
        debt_issues: list[str] = [desc for pattern, desc in _EXEC_HACK_PATTERNS if pattern.search(text)]
        passed_debt = len(debt_issues) == 0
        compromises.extend(debt_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[1].name,
                role=team.personas[1].role,
                passed=passed_debt,
                critique=(
                    "Zero technical debt, hacks, or shortcuts found. Code meets long-term standards."
                    if passed_debt
                    else f"Discovered {len(debt_issues)} technical debt compromise(s) an executive would reject."
                ),
                issues=debt_issues,
                recommendations=["Replace temporary hacks and shortcuts with clean, permanent architecture."] if debt_issues else [],
            )
        )

        # 3. Product Director
        product_issues: list[str] = []
        if _EXEC_PRODUCT_RE.search(text):
            product_issues.append("Feature incomplete or confusing user flow")

        passed_product = len(product_issues) == 0
        if product_issues:
            defects.extend(product_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[2].name,
                role=team.personas[2].role,
                passed=passed_product,
                critique=(
                    "The feature fulfills the user's requirements stress-free."
                    if passed_product
                    else f"Flagged {len(product_issues)} product experience issue(s)."
                ),
                issues=product_issues,
                recommendations=["Complete all promised functionality with clear, welcoming feedback."] if product_issues else [],
            )
        )

        overall_passed = (len(defects) == 0) and (len(compromises) == 0)
        living_room = self._format_living_room_verdict(
            team=team,
            passed=overall_passed,
            defects=defects,
            compromises=compromises,
            critiques=critiques,
        )

        return TeamReviewVerdict(
            team_type=team.team_id,
            team_name=team.name,
            passed=overall_passed,
            living_room_verdict=living_room,
            critiques=critiques,
            defects=defects,
            compromises=compromises,
            metadata={"compromises_count": len(compromises)},
        )

    def _synthesize_integration_review(self, team: SubagentTeam, text: str) -> TeamReviewVerdict:
        """Synthesizes review for System Integration Team (wiring, regressions, state sync)."""
        defects: list[str] = []
        critiques: list[PersonaCritique] = []

        # 1. Wiring Logic Auditor
        wiring_issues: list[str] = [desc for pattern, desc in _INTEG_WIRING_PATTERNS if pattern.search(text)]
        passed_wiring = len(wiring_issues) == 0
        defects.extend(wiring_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[0].name,
                role=team.personas[0].role,
                passed=passed_wiring,
                critique=(
                    "All caller/callee signatures, arguments, and public exports are cleanly wired."
                    if passed_wiring
                    else f"Discovered {len(wiring_issues)} wiring logic defect(s)."
                ),
                issues=wiring_issues,
                recommendations=["Fix component imports and ensure arguments match target signatures."] if wiring_issues else [],
            )
        )

        # 2. Regressions Checker
        reg_issues: list[str] = []
        if _INTEG_REGRESSION_RE.search(text):
            reg_issues.append("Regression detected against existing codebase tests or models")

        passed_reg = len(reg_issues) == 0
        defects.extend(reg_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[1].name,
                role=team.personas[1].role,
                passed=passed_reg,
                critique=(
                    "100% backward-compatible. Existing test suites and interfaces remain green."
                    if passed_reg
                    else f"Flagged {len(reg_issues)} backward-compatibility regression(s)."
                ),
                issues=reg_issues,
                recommendations=["Restore backward compatibility for existing callers."] if reg_issues else [],
            )
        )

        # 3. State Sync Specialist
        state_issues: list[str] = []
        if _INTEG_STATE_RE.search(text):
            state_issues.append("State synchronization or atomic persistence failure")

        passed_state = len(state_issues) == 0
        defects.extend(state_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[2].name,
                role=team.personas[2].role,
                passed=passed_state,
                critique=(
                    "Atomic persistence and thread-safe state synchronization verified."
                    if passed_state
                    else f"Found {len(state_issues)} state synchronization flaw(s)."
                ),
                issues=state_issues,
                recommendations=["Ensure atomic save routines and thread locks are in place."] if state_issues else [],
            )
        )

        overall_passed = len(defects) == 0
        living_room = self._format_living_room_verdict(
            team=team,
            passed=overall_passed,
            defects=defects,
            compromises=[],
            critiques=critiques,
        )

        return TeamReviewVerdict(
            team_type=team.team_id,
            team_name=team.name,
            passed=overall_passed,
            living_room_verdict=living_room,
            critiques=critiques,
            defects=defects,
            compromises=[],
            metadata={"wiring_defects": len(wiring_issues)},
        )

    def _synthesize_visual_review(self, team: SubagentTeam, text: str) -> TeamReviewVerdict:
        """Synthesizes review for Visual Proof Team (screenshots, 6-lens craft, walkthrough)."""
        defects: list[str] = []
        critiques: list[PersonaCritique] = []

        # 1. Screenshot / Simulator Verifier
        visual_issues: list[str] = [desc for pattern, desc in _VISUAL_CRAFT_PATTERNS if pattern.search(text)]
        passed_visual = len(visual_issues) == 0
        defects.extend(visual_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[0].name,
                role=team.personas[0].role,
                passed=passed_visual,
                critique=(
                    "Visual proof verified. 6-Lens Micro-Craft standards are 100% satisfied."
                    if passed_visual
                    else f"Flagged {len(visual_issues)} visual or ergonomic flaw(s)."
                ),
                issues=visual_issues,
                recommendations=["Adjust hitboxes to minimum 44px and enforce 4/8pt spatial grid."] if visual_issues else [],
            )
        )

        # 2. Walkthrough Auditor
        walk_issues: list[str] = []
        if len(text.strip()) < 20:
            walk_issues.append("Walkthrough summary is incomplete or empty")

        passed_walk = len(walk_issues) == 0
        defects.extend(walk_issues)
        critiques.append(
            PersonaCritique(
                persona_name=team.personas[1].name,
                role=team.personas[1].role,
                passed=passed_walk,
                critique=(
                    "The user journey walkthrough is complete and verified end-to-end."
                    if passed_walk
                    else "Walkthrough narrative is incomplete."
                ),
                issues=walk_issues,
                recommendations=["Provide a clear step-by-step description of the user experience."] if walk_issues else [],
            )
        )

        overall_passed = len(defects) == 0
        living_room = self._format_living_room_verdict(
            team=team,
            passed=overall_passed,
            defects=defects,
            compromises=[],
            critiques=critiques,
        )

        return TeamReviewVerdict(
            team_type=team.team_id,
            team_name=team.name,
            passed=overall_passed,
            living_room_verdict=living_room,
            critiques=critiques,
            defects=defects,
            compromises=[],
            metadata={"visual_flaws": len(visual_issues)},
        )

    def _synthesize_generic_review(self, team: SubagentTeam, text: str) -> TeamReviewVerdict:
        """Generic fallback review synthesis."""
        has_failure = bool(_GENERIC_FAILURE_RE.search(text))
        critique = PersonaCritique(
            persona_name=team.personas[0].name if team.personas else "Auditor",
            role="general_auditor",
            passed=not has_failure,
            critique="Generic audit completed." if not has_failure else "Execution failure reported.",
            issues=["Generic failure marker in output"] if has_failure else [],
        )
        return TeamReviewVerdict(
            team_type=team.team_id,
            team_name=team.name,
            passed=not has_failure,
            living_room_verdict="All checks passed." if not has_failure else "Issues were found.",
            critiques=[critique],
            defects=["General execution defect"] if has_failure else [],
            compromises=[],
        )

    def _format_living_room_verdict(
        self,
        team: SubagentTeam,
        passed: bool,
        defects: list[str],
        compromises: list[str],
        critiques: list[PersonaCritique],
    ) -> str:
        """Enforces the Living-Room Test: clear, warm, zero-plumbing human English."""
        canonical = team.team_id

        if passed:
            if canonical in ("qa_team", "qa_team_2"):
                return "The code is solid. All three QA auditors checked edge cases, security, and tests, and found zero issues."
            elif canonical == "executive_team":
                return "Approved with zero compromises. The design is clean, simple, and ready for customers without any hacks or shortcuts."
            elif canonical == "system_integration_team":
                return "Fully wired and synced. All components connect cleanly with the existing codebase and no regressions were introduced."
            elif canonical == "visual_proof_team":
                return "The user experience looks great. All screens follow our design standards, and the walkthrough verified smooth end-to-end interactions."
            return "Everything looks great. The team verified the work and approved it with zero issues."

        # Rejected cases
        if canonical in ("qa_team", "qa_team_2"):
            first_issue = defects[0] if defects else "quality defect"
            count = len(defects)
            return f"The QA team flagged {count} issue{'s' if count > 1 else ''} that must be fixed before release: {first_issue}."
        elif canonical == "executive_team":
            first_comp = (compromises + defects)[0] if (compromises or defects) else "architectural shortcut"
            return f"The executive team rejected this version because of shortcuts in the code: {first_comp}. These must be cleaned up to meet our quality bar."
        elif canonical == "system_integration_team":
            first_defect = defects[0] if defects else "integration flaw"
            count = len(defects)
            return f"The system review caught {count} integration issue{'s' if count > 1 else ''}: {first_defect}. The connections between components need to be fixed."
        elif canonical == "visual_proof_team":
            first_defect = defects[0] if defects else "visual rough edge"
            count = len(defects)
            return f"The visual check found {count} rough edge{'s' if count > 1 else ''}: {first_defect}. The interface needs to be polished before release."

        first_err = (defects + compromises)[0] if (defects or compromises) else "flaw"
        return f"The team found issues that need to be resolved: {first_err}."

    # ----------------------------------------------------------------------
    # Screenshot Evidence Manifest: generate_screenshot_evidence_manifest
    # ----------------------------------------------------------------------

    def generate_screenshot_evidence_manifest(
        self,
        image_paths: list[str],
        walkthrough_summary: str,
        step_index: int = 6,
        feature_name: str = "Feature Implementation",
        passed: bool = True,
        defects: Optional[list[str]] = None,
    ) -> str:
        """Formats visual screenshot proof into a Stratum 3 Milestone Card.

        Anchors visual proof in a compact, typed Markdown receipt (~200-300 tokens)
        preserving context hygiene without carrying raw image tokens across turns.
        """
        clean_paths = [str(p).strip() for p in image_paths if str(p).strip()]

        # Format image gallery
        if clean_paths:
            gallery_lines: list[str] = []
            for idx, p in enumerate(clean_paths, 1):
                p_obj = Path(p)
                label = f"Screenshot {idx}: {p_obj.stem.replace('_', ' ').title()}"
                gallery_lines.append(f"- **{label}** (`{p}`)")
                gallery_lines.append(f"  ![{label}]({p})")
            gallery_block = "\n".join(gallery_lines)
        else:
            gallery_block = "*No visual screenshot images were attached to this turn.*"

        clean_summary = walkthrough_summary.strip() or "*Visual verification completed successfully.*"

        defect_blob = " ".join(defects).lower() if defects else ""
        def has_defect(*keywords: str) -> bool:
            return any(k in defect_blob for k in keywords)

        check = "[x]" if passed else "[ ]"
        check_radii = "[ ]" if has_defect("radi") else check
        check_rhythm = "[ ]" if has_defect("rhythm", "grid") else check
        check_touch = "[ ]" if has_defect("touch", "44") else check
        check_contrast = "[ ]" if has_defect("contrast", "leading") else check
        check_state = "[ ]" if has_defect("state", "hover") else check

        return (
            f"## 📍 Visual Proof Milestone Manifest — Step {step_index}: {feature_name}\n\n"
            f"- **Stratum:** Stratum 3 (Structured Milestone Manifest)\n"
            f"- **Step Index:** {step_index}\n"
            f"- **Artifact Type:** Visual Proof & Simulator Walkthrough\n"
            f"- **Screenshots Verified:** {len(clean_paths)}\n\n"
            f"### 🖼️ Screenshot Evidence Gallery\n"
            f"{gallery_block}\n\n"
            f"### 🔍 Optical & Ergonomic Craft Audit (6-Lens Standard)\n"
            f"- {check_radii} **Concentric Radii:** Inner corners match $R_{{inner}} = \\max(0, R_{{outer}} - P)$\n"
            f"- {check_rhythm} **Strict 4/8pt Rhythm:** Zero arbitrary off-grid pixel margins or paddings\n"
            f"- {check_touch} **Touch Ergonomics:** All interactive hitboxes meet minimum 44x44px target\n"
            f"- {check_contrast} **Contrast & Typography:** Crisp text contrast and balanced headline leading\n"
            f"- {check_state} **State Completeness:** Default, hover, active, and loading states verified\n\n"
            f"### 🚶 User Walkthrough Summary\n"
            f"{clean_summary}\n\n"
            f"---\n"
            f"*Context Ledger Anchor: Compact persistent milestone handoff for visual verification.*"
        )

    def evaluate_step(
        self,
        step_idx: int,
        step_output: str,
        image_paths: Optional[list[str]] = None,
    ) -> TeamReviewVerdict:
        """Convenience method to evaluate any of the 6 canonical workflow steps."""
        # Step 0 / 1: Initial Prompt -> Code feature (QA Team 1 review)
        # Step 2: Auto reply 1 -> QA Team 1
        # Step 3: Auto reply 2 -> QA Team 2
        # Step 4: Auto reply 3 -> Executive Review Team
        # Step 5: Auto reply 4 -> System Integration Team
        # Step 6: Auto reply 5 & 6 -> Visual Proof Team
        step_mapping = {
            0: "qa_team",
            1: "qa_team",
            2: "qa_team_2",
            3: "executive_team",
            4: "system_integration_team",
            5: "visual_proof_team",
            6: "visual_proof_team",
        }
        team_id = step_mapping.get(step_idx, "qa_team")
        verdict = self.synthesize_team_review(team_id, step_output)

        if team_id == "visual_proof_team" and image_paths:
            manifest = self.generate_screenshot_evidence_manifest(
                image_paths=image_paths,
                walkthrough_summary=step_output,
                step_index=step_idx + 1 if step_idx < 6 else 6,
                passed=verdict.passed,
                defects=verdict.defects,
            )
            verdict.metadata["milestone_card"] = manifest

        return verdict
